[2021-07-14 22:55:01,687] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-07-13T00:00:00+00:00 [queued]>
[2021-07-14 22:55:01,697] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-07-13T00:00:00+00:00 [queued]>
[2021-07-14 22:55:01,697] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-14 22:55:01,698] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-14 22:55:01,698] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-14 22:55:01,704] {taskinstance.py:1107} INFO - Executing <Task(SqliteOperator): creating_table> on 2021-07-13T00:00:00+00:00
[2021-07-14 22:55:01,708] {standard_task_runner.py:52} INFO - Started process 6080 to run task
[2021-07-14 22:55:01,709] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'creating_table', '2021-07-13T00:00:00+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpu0z5dpug', '--error-file', '/tmp/tmpku0yat00']
[2021-07-14 22:55:01,709] {standard_task_runner.py:77} INFO - Job 17: Subtask creating_table
[2021-07-14 22:55:01,736] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.creating_table 2021-07-13T00:00:00+00:00 [running]> on host 120364900fc4
[2021-07-14 22:55:01,764] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2021-07-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-13T00:00:00+00:00
[2021-07-14 22:55:01,764] {sqlite.py:61} INFO - Executing: 
            CREATE TABLE users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
            
[2021-07-14 22:55:01,769] {base.py:78} INFO - Using connection to: id: db_sqlite. Host: /opt/***/***.db, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-14 22:55:01,772] {dbapi.py:204} INFO - Running statement: 
            CREATE TABLE users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
            , parameters: []
[2021-07-14 22:55:01,773] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/sqlite/operators/sqlite.py", line 63, in execute
    hook.run(self.sql, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: table users already exists
[2021-07-14 22:55:01,774] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=user_processing, task_id=creating_table, execution_date=20210713T000000, start_date=20210714T225501, end_date=20210714T225501
[2021-07-14 22:55:01,801] {local_task_job.py:151} INFO - Task exited with return code 1
