[2021-07-17 13:57:07,951] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-04-19T00:00:00+00:00 [queued]>
[2021-07-17 13:57:07,972] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-04-19T00:00:00+00:00 [queued]>
[2021-07-17 13:57:07,974] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:57:07,974] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-17 13:57:07,983] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:57:08,001] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-04-19T00:00:00+00:00
[2021-07-17 13:57:08,006] {standard_task_runner.py:52} INFO - Started process 7999 to run task
[2021-07-17 13:57:08,018] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-04-19T00:00:00+00:00', '--job-id', '565', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9y9ugq69', '--error-file', '/tmp/tmplai2mqn2']
[2021-07-17 13:57:08,018] {standard_task_runner.py:77} INFO - Job 565: Subtask is_api_available
[2021-07-17 13:57:08,124] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-04-19T00:00:00+00:00 [running]> on host 120364900fc4
[2021-07-17 13:57:08,244] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-04-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-19T00:00:00+00:00
[2021-07-17 13:57:08,244] {http.py:101} INFO - Poking: api/
[2021-07-17 13:57:08,260] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-17 13:57:08,262] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-07-17 13:57:08,577] {base.py:248} INFO - Success criteria met. Exiting.
[2021-07-17 13:57:08,593] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200419T000000, start_date=20210717T135707, end_date=20210717T135708
[2021-07-17 13:57:08,670] {local_task_job.py:151} INFO - Task exited with return code 1
