[2021-07-17 13:57:42,380] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user 2020-05-03T00:00:00+00:00 [queued]>
[2021-07-17 13:57:42,404] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user 2020-05-03T00:00:00+00:00 [queued]>
[2021-07-17 13:57:42,404] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:57:42,404] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-17 13:57:42,404] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:57:42,423] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): storing_user> on 2020-05-03T00:00:00+00:00
[2021-07-17 13:57:42,427] {standard_task_runner.py:52} INFO - Started process 8331 to run task
[2021-07-17 13:57:42,429] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'storing_user', '2020-05-03T00:00:00+00:00', '--job-id', '671', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpiuyqsbb_', '--error-file', '/tmp/tmp884t_7cz']
[2021-07-17 13:57:42,430] {standard_task_runner.py:77} INFO - Job 671: Subtask storing_user
[2021-07-17 13:57:42,462] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.storing_user 2020-05-03T00:00:00+00:00 [running]> on host 120364900fc4
[2021-07-17 13:57:42,541] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=storing_user
AIRFLOW_CTX_EXECUTION_DATE=2020-05-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-05-03T00:00:00+00:00
[2021-07-17 13:57:42,542] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-17 13:57:42,542] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo -e ".separator ","\n.import /tmp/processed_user.csv users" | sqlite3 /opt/***/***.db']
[2021-07-17 13:57:42,551] {subprocess.py:75} INFO - Output:
[2021-07-17 13:57:42,553] {subprocess.py:79} INFO - Error: database is locked
[2021-07-17 13:57:42,553] {subprocess.py:83} INFO - Command exited with return code 1
[2021-07-17 13:57:42,560] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-17 13:57:42,561] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=user_processing, task_id=storing_user, execution_date=20200503T000000, start_date=20210717T135742, end_date=20210717T135742
[2021-07-17 13:57:42,601] {local_task_job.py:151} INFO - Task exited with return code 1
