[2021-07-17 13:56:08,473] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-03-10T00:00:00+00:00 [queued]>
[2021-07-17 13:56:08,491] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-03-10T00:00:00+00:00 [queued]>
[2021-07-17 13:56:08,491] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:56:08,491] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-17 13:56:08,491] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:56:08,508] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-03-10T00:00:00+00:00
[2021-07-17 13:56:08,513] {standard_task_runner.py:52} INFO - Started process 7409 to run task
[2021-07-17 13:56:08,525] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-03-10T00:00:00+00:00', '--job-id', '370', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpga774xox', '--error-file', '/tmp/tmp0d43a0oj']
[2021-07-17 13:56:08,526] {standard_task_runner.py:77} INFO - Job 370: Subtask is_api_available
[2021-07-17 13:56:08,564] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-03-10T00:00:00+00:00 [running]> on host 120364900fc4
[2021-07-17 13:56:08,620] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-03-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-10T00:00:00+00:00
[2021-07-17 13:56:08,620] {http.py:101} INFO - Poking: api/
[2021-07-17 13:56:08,630] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-17 13:56:08,633] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-07-17 13:56:08,931] {base.py:248} INFO - Success criteria met. Exiting.
[2021-07-17 13:56:08,956] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200310T000000, start_date=20210717T135608, end_date=20210717T135608
[2021-07-17 13:56:09,013] {local_task_job.py:151} INFO - Task exited with return code 1
