[2021-07-15 21:42:07,993] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user 2020-01-14T00:00:00+00:00 [queued]>
[2021-07-15 21:42:08,004] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user 2020-01-14T00:00:00+00:00 [queued]>
[2021-07-15 21:42:08,004] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 21:42:08,004] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-15 21:42:08,004] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 21:42:08,011] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): storing_user> on 2020-01-14T00:00:00+00:00
[2021-07-15 21:42:08,015] {standard_task_runner.py:52} INFO - Started process 5412 to run task
[2021-07-15 21:42:08,018] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'storing_user', '2020-01-14T00:00:00+00:00', '--job-id', '105', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpa66h9j1k', '--error-file', '/tmp/tmp2pvshnpv']
[2021-07-15 21:42:08,018] {standard_task_runner.py:77} INFO - Job 105: Subtask storing_user
[2021-07-15 21:42:08,048] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.storing_user 2020-01-14T00:00:00+00:00 [running]> on host 120364900fc4
[2021-07-15 21:42:08,084] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=storing_user
AIRFLOW_CTX_EXECUTION_DATE=2020-01-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-14T00:00:00+00:00
[2021-07-15 21:42:08,085] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-15 21:42:08,085] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo -e ".separator ","\n.import /tmp/processed_user.csv users" | sqlite3 /opt/***/***.db']
[2021-07-15 21:42:08,094] {subprocess.py:75} INFO - Output:
[2021-07-15 21:42:08,095] {subprocess.py:79} INFO - /tmp/processed_user.csv:1: INSERT failed: UNIQUE constraint failed: users.email
[2021-07-15 21:42:08,096] {subprocess.py:83} INFO - Command exited with return code 1
[2021-07-15 21:42:08,102] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-15 21:42:08,103] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=user_processing, task_id=storing_user, execution_date=20200114T000000, start_date=20210715T214207, end_date=20210715T214208
[2021-07-15 21:42:08,150] {local_task_job.py:151} INFO - Task exited with return code 1
